import React, { useState } from 'react';
import { TextInput, useWindowDimensions, View } from 'react-native';
import { Shell } from '../components/Shell';
import { Button, Icon, Pill, s, T } from '../components/ui';
import { useApp } from '../context/AppContext';
import { colors as c, fonts as f } from '../theme';

export default function Account() {
  const app = useApp(); const { width } = useWindowDimensions(); const [name, setName] = useState(app.name); const [saved, setSaved] = useState(false); const [note, setNote] = useState(''); const [sent, setSent] = useState(false);
  return <Shell><T style={s.label}>A LITTLE ABOUT YOU</T><T style={[s.title, { marginTop: 10 }]}>Your account</T><T style={[s.muted, { marginTop: 8, marginBottom: 28 }]}>Your rainy-day essentials, all in one place.</T>
    <View style={{ flexDirection: width < 850 ? 'column' : 'row', gap: 24 }}><View style={{ flex: 1, gap: 22 }}>
      <View style={[s.card, { gap: 21 }]}><View style={s.row}><View style={{ height: 58, width: 58, borderRadius: 20, alignItems: 'center', justifyContent: 'center', backgroundColor: c.mint }}><Icon name="user" size={27} /></View><View style={{ gap: 5 }}><T style={{ fontFamily: f.bold, fontSize: 20 }}>{app.name || 'Hello, rain explorer.'}</T><Pill tone="orange">Local demo profile</Pill></View></View><View style={{ gap: 8 }}><T style={{ fontSize: 12, fontFamily: f.semibold }}>First name</T><TextInput accessibilityLabel="Profile name" style={s.input} value={name} onChangeText={v => { setName(v); setSaved(false); }} maxLength={40} placeholder="Your first name" placeholderTextColor={c.muted} /></View><Button title={saved ? 'Name saved' : 'Save profile'} icon={saved ? 'check' : 'user'} disabled={!name.trim()} onPress={() => { app.saveName(name); setSaved(true); }} /><T style={{ color: c.muted, fontSize: 11, lineHeight: 17 }}>This profile lives only on this device. Account sign-in and syncing will be connected to the backend.</T></View>
      <View style={[s.card, { gap: 18 }]}><View style={s.row}><Icon name="credit-card" /><T style={{ fontFamily: f.bold, fontSize: 18 }}>Payment method</T></View><View style={[s.between, { backgroundColor: c.cream, borderRadius: 12, padding: 18 }]}><View><T style={{ fontFamily: f.semibold }}>Demo wallet</T><T style={{ fontSize: 12, color: c.muted, marginTop: 5 }}>Ready for simulated rentals</T></View><Pill>No charges</Pill></View><T style={s.muted}>You won’t be asked for card details in this preview.</T></View>
      <View style={[s.card, { gap: 12 }]}><T style={{ fontFamily: f.bold, fontSize: 18 }}>Your shared moments</T><View style={{ flexDirection: 'row', gap: 30 }}><View><T style={{ fontFamily: f.display, fontSize: 38 }}>{app.history.length}</T><T style={{ color: c.muted, fontSize: 12 }}>Completed rentals</T></View><View><T style={{ fontFamily: f.display, fontSize: 38 }}>{app.favorites.length}</T><T style={{ color: c.muted, fontSize: 12 }}>Saved stations</T></View></View></View>
    </View><View style={{ flex: 1, gap: 22 }}>
      <View style={[s.card, { gap: 17 }]}><View style={s.row}><Icon name="life-buoy" /><T style={{ fontFamily: f.bold, fontSize: 18 }}>A little help?</T></View><T style={s.muted}>Umbrella stuck, trouble returning, or something else? Describe what happened.</T><TextInput accessibilityLabel="Describe your issue" multiline style={[s.input, { minHeight: 130, textAlignVertical: 'top' }]} value={note} onChangeText={v => { setNote(v); setSent(false); }} placeholder="Station name, umbrella number, and the issue…" placeholderTextColor={c.muted} maxLength={1000} /><Button title={sent ? 'Saved on this device' : 'Save demo support request'} icon={sent ? 'check' : 'message-circle'} disabled={note.trim().length < 10 || sent} onPress={() => { app.report(note.trim()); setSent(true); }} /><T accessibilityRole={sent ? 'alert' : undefined} style={{ color: c.muted, fontSize: 11, lineHeight: 18 }}>{sent ? 'Your note is saved locally. It has not been sent to a support team.' : 'At least 10 characters. Demo requests are saved locally and are not sent to a support team.'}</T>{app.reports.length > 0 && <T style={{ color: c.green, fontSize: 12 }}>{app.reports.length} request{app.reports.length === 1 ? '' : 's'} saved on this device</T>}</View>
      <View style={[s.card, { gap: 14 }]}><View style={s.row}><Icon name="shield" /><T style={{ fontFamily: f.bold, fontSize: 18 }}>Your location stays yours.</T></View><T style={s.muted}>We ask for your location only when you tap the location button. No background tracking. Prefer not to share? Search the map manually.</T><T style={{ fontSize: 11, color: c.muted, lineHeight: 17 }}>Station availability and prices are examples. Live stations, payments, account authentication, and support require backend integration.</T></View>
    </View></View>
  </Shell>;
}
